//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use core::fmt;
use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)", enum_name = "indicator_type", rename_all = "UPPERCASE")]
pub enum IndicatorType{
    RSI,
    Price
}

impl fmt::Display for IndicatorType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            IndicatorType::RSI => write!(f, "RSI"),
            IndicatorType::Price => write!(f, "Price")
        }
    }
}


#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)", enum_name = "interval", rename_all = "UPPERCASE")]
pub enum Interval{
    Minute,
    FiveMinutes,
    FifteenMinutes,
    ThirtyMinutes,
    SixtyMinutes
}

impl fmt::Display for Interval {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Interval::Minute => write!(f, "MINUTE"),
            Interval::FiveMinutes => write!(f, "FIVEMINUTES"),
            Interval::FifteenMinutes => write!(f, "FIFTEENMINUTES"),
            Interval::ThirtyMinutes => write!(f, "THIRTYMINUTES"),
            Interval::SixtyMinutes => write!(f, "SIXTYMINUTES")
        }
    }
}

impl Interval{
    pub fn from_string(interval: &str) -> Option<Interval>{
        match interval{
            "1" => Some(Interval::Minute),
            "5" => Some(Interval::FiveMinutes),
            "15" => Some(Interval::FifteenMinutes),
            "30" => Some(Interval::ThirtyMinutes),
            "60" => Some(Interval::SixtyMinutes),
            _ => None
        }
    }
}


#[derive(Clone, Debug, DeriveEntityModel)]
#[sea_orm(table_name = "indicators")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub symbol_id: i32,
    pub value: f32,
    pub indicator_type: IndicatorType,
    pub interval: Interval,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::symbols::Entity",
        from = "Column::SymbolId",
        to = "super::symbols::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Symbols,
}

impl Related<super::symbols::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Symbols.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
