//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "indicators")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub symbol_id: i32,
    pub value: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::symbols::Entity",
        from = "Column::SymbolId",
        to = "super::symbols::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Symbols,
}

impl Related<super::symbols::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Symbols.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
