//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)", enum_name = "indicator_type", rename_all = "UPPERCASE")]
pub enum IndicatorType{
    RSI,
    Price
}


#[derive(Clone, Debug, DeriveEntityModel)]
#[sea_orm(table_name = "indicators")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub symbol_id: i32,
    pub value: f32,
    pub indicator_type: IndicatorType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::symbols::Entity",
        from = "Column::SymbolId",
        to = "super::symbols::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Symbols,
}

impl Related<super::symbols::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Symbols.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
