//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "symbols")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub tile: String,
    pub exchange_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::exchanges::Entity",
        from = "Column::ExchangeId",
        to = "super::exchanges::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Exchanges,
    #[sea_orm(has_many = "super::indicators::Entity")]
    Indicators,
}

impl Related<super::exchanges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Exchanges.def()
    }
}

impl Related<super::indicators::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Indicators.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
